- name: Apache Installation
  hosts: localhost
  vars_files:
    - ../var/settings.yml

  tasks:
  - name: General | Install Apache packages
    apt: "name={{ item }} state=present"
    with_items:
      - php5
      - apache2
      - php5-mysql
      - php-apc
      - php5-xmlrpc
      - php-soap
      - php5-gd
      - php5-curl
      - sendmail
      - unzip

  - name: Apache | Enable php modules
    apache2_module: "name={{ item }} state=present"
    with_items:
      - php5
      - proxy
      - proxy_http
      - headers
      - rewrite
      - dir

  - name: Apache | Remove default site
    file: path=/etc/apache2/sites-enabled/000-default state=absent

  - name: Apache | Configuration file /etc/php5/apache2/php.ini
    template: 
      src: ../templates/php.ini
      dest: /etc/php5/apache2/php.ini
      owner: root
      mode: 0755

  - name: Apache | Auto start the Apache service
    service: 
      name: apache2 
      state: started
      enabled: yes
